# Generated by Django 5.1 on 2025-04-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='usuario',
        ),
    ]
