# Generated by Django 5.1 on 2025-04-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_cuota_monto_remove_cuota_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
