# Generated by Django 5.1 on 2025-04-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_reporte_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='salario',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
