# Generated by Django 5.1 on 2025-05-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_salario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='asistencias',
        ),
        migrations.DeleteModel(
            name='Cuota',
        ),
        migrations.DeleteModel(
            name='Parte',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
