# Generated by Django 5.1 on 2025-05-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindicato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporte',
            new_name='Acta',
        ),
        migrations.RenameField(
            model_name='cuota',
            old_name='reporte',
            new_name='acta',
        ),
    ]
