# Generated by Django 5.1 on 2025-05-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindicato', '0002_rename_reporte_acta_rename_reporte_cuota_acta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='fecha',
        ),
    ]
